### ISSUE TITLE
Documentation for ASP core is broken and compile issues

### ISSUE THREAD

**Issue by weedkiller** [creativetimofficial/argon-dashboard-asp-net#13]
Hello this is nice, but its not working and the _help is also broken on your site._

- [ ] Documentation link, components, demo, etc.. link on your site is broken
- [ ] Also there are some minor compile errors with the current bootstrap and nuget component. Could you update to ASP core 5.0.3

![image](https://user-images.githubusercontent.com/21086190/120051503-e0d35500-bfee-11eb-9f28-6f4a7302822b.png)

**Comment by 17Pixelz** [comment]
You can get the documentation on the file "{Your Project Folder}/docs/documentation.html".

**Comment by weedkiller** [comment]
thanks, also its not compiling on .net core 5 i tried older and current versions.

After updating the nugets the errors went down significantly, the last two I was unable to resolve
